### ISSUE TITLE
Data Cleaning

### ISSUE THREAD

**Issue by chris-prener** [stlrda/AI_Assessor#1]
Initial repo clean-up tasks for @bransonf:

- [x] Replace `.gitignore` with standard template
- [x] Remove `.DS_Store`
- [x] Move `.xml` and `.xlsx` files to `resources/`
- [x] add script for converting crazy csv to .rda
- [x] save compressed .rda, move raw data to `data/raw`
- [x] add `.Rproj` back in
- [x] fold libraries / data download into initial .Rmd
- [x] create `docs/`
- [x] add templated `.Rmd` file

Initial repo clean-up tasks for @chris-prener:
- [x] load `.rda` data into second notebook
- [ ] clean-up subsetting process
- [ ] join tables
- [ ] bin radius data
- [ ] check for additional variables
- [ ] write analytic data to `.csv`

**Comment by chris-prener** [comment]
@bransonf - I know you did some additional work here - do any of these tasks still need to be done?

**Comment by bransonf** [comment]
Closing for project restructure. Entire data process needs to be converted from Tableau/Alteryx
