### ISSUE TITLE
Organize volunteers into teams

### ISSUE THREAD

**Issue by jonathanleek** [stlrda/AI_Assessor#13]
See the slack conversation we had about this, but having the teams pre-defined would be helpful. This is low priority, we can always do it day of if necessary.

**Comment by bransonf** [comment]
I think teams should more or less be divided as projects is currently.  
- Data Team
- AI Team
- Viz Team
- Dev Ops Team

**Comment by palatiner** [comment]
So is this something we plan on doing as step 1 on Sunday to kick things off?
